version: '3'
services:
  database:
    # Dockerfile이 있는 위치
    build: ./Database
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "3306:3306"
    platform: linux/x86_64 #when if you are using M1
  backend:
    build: ./Backend
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./Backend:/usr/src/app
    ports:
      - "4000:4000"
    # 환경변수 설정
    environment: 
      - DBHOST=database
  frontend:
    build: ./frontend
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./Frontend:/home/node/app
    ports:
      - "8485:8484"