FROM python:3.8.10

RUN pip3 install flask flask-cors flask-mysql

WORKDIR /usr/src/app

CMD ["python3", "main.py"]

# 이미지 생성 명령어 (현 파일과 같은 디렉토리에서)
# docker build -t {이미지명} .

# 컨테이너 생성 & 실행 명령어
# docker run --name {컨테이너명} -v $(pwd):/usr/src/app -p 5000:5000 {이미지명}